// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_niym6vfO9xpf9__VcR4Ne364wor3kYo',
    appId: '1:914279297926:web:ea35c48fcdb2cbc68f7207',
    messagingSenderId: '914279297926',
    projectId: 'hospital-lover',
    authDomain: 'hospital-lover.firebaseapp.com',
    storageBucket: 'hospital-lover.appspot.com',
    measurementId: 'G-5Q67MDNZV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUceYJchob-iY2nt2JTdzh4R8bt6kmVIs',
    appId: '1:914279297926:android:606a532ebdf6acd48f7207',
    messagingSenderId: '914279297926',
    projectId: 'hospital-lover',
    storageBucket: 'hospital-lover.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyA-1MbovXTw3p1jGj0vfM22I2G-plN38',
    appId: '1:914279297926:ios:785b3a405a79a6ec8f7207',
    messagingSenderId: '914279297926',
    projectId: 'hospital-lover',
    storageBucket: 'hospital-lover.appspot.com',
    iosClientId: '914279297926-v99uv4g49u4e9db7m2bhem819bsv7v8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplate',
  );
}
