// This file is "base_model.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `base_model.dart` with the code generated by Freezed
part 'base_model.freezed.dart';
// optional: Since our BaseModel class is serializable(JSON), we must add this line.
// But if BaseModel was not serializable, we could skip it.
part 'base_model.g.dart';

@freezed
class BaseRequest with _$BaseRequest {
  const factory BaseRequest({
    required String service,
  }) = _BaseRequest;

  factory BaseRequest.fromJson(Map<String, Object?> json) =>
      _$BaseRequestFromJson(json);
}

@freezed
class BaseResponse with _$BaseResponse {
  const factory BaseResponse({
    int? result,
    String? message,
    String? token,
    int? loginProvider,
  }) = _BaseResponse;

  factory BaseResponse.fromJson(Map<String, Object?> json) =>
      _$BaseResponseFromJson(json);
}
