// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_template/test/screen/home/home_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_template/base/base_service.dart' as _i4;
import 'package:flutter_template/service/login/list_staff_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeListStaffServiceResponse_0 extends _i1.SmartFake
    implements _i2.ListStaffServiceResponse {
  _FakeListStaffServiceResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ListStaffService].
///
/// See the documentation for Mockito's code generation for more information.
class MockListStaffService extends _i1.Mock implements _i2.ListStaffService {
  @override
  _i3.Future<_i2.ListStaffServiceResponse> callService(
          _i2.ListStaffServiceRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #callService,
          [request],
        ),
        returnValue: _i3.Future<_i2.ListStaffServiceResponse>.value(
            _FakeListStaffServiceResponse_0(
          this,
          Invocation.method(
            #callService,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.ListStaffServiceResponse>.value(
                _FakeListStaffServiceResponse_0(
          this,
          Invocation.method(
            #callService,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.ListStaffServiceResponse>);
  @override
  _i3.Future<String> execute(
    _i4.ServiceUrl? url, {
    required Map<String, dynamic>? request,
    required _i4.HttpMethod? method,
    _i4.UrlType? urlType = _i4.UrlType.deufaultUrl,
    String? unencodePath,
    bool? needAuth = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [url],
          {
            #request: request,
            #method: method,
            #urlType: urlType,
            #unencodePath: unencodePath,
            #needAuth: needAuth,
          },
        ),
        returnValue: _i3.Future<String>.value(''),
        returnValueForMissingStub: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
}
